name: Update nixpkgs-lock pin

on:
  schedule:
    - cron: '30 3 * * *'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v27

      - run: nix flake update nixpkgs-lock

      - run: nix flake check --no-build

      - uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "chore: update nixpkgs-lock pin"
          title: "chore: update nixpkgs-lock pin"
          branch: auto/pin-update
          delete-branch: true
          labels: auto-merge
          author: Marcin Nowicki <pr0d1r2@gmail.com>
          committer: Marcin Nowicki <pr0d1r2@gmail.com>
